# This file contains the functions necessary for the project.

import time


# Function for finding the desired department
# in the supermarket.
def find_store_department(product_name):
    print('')
    print(f'Вам нужен отдел, где продаётся "{product_name}".')
    time.sleep(1)
    print('')
    print('Если нашли - введите слово "да".')
    print('')
    time.sleep(1)
    print('    Если не нашли - слово "нет".')
    time.sleep(1)
    department_found = (input('=> ')).lower()
    if department_found == 'да':
        print('')
        time.sleep(1)
        print(f'Отлично! В этом отделе попытайтесь найти "{product_name}".')
    elif department_found == 'нет':
        print('')
        time.sleep(1)
        print('Спросите пожалуйста у кого-то из персонала:')
        print('')
        time.sleep(1)
        print(f'"В каком отделе продаётся "{product_name}"?".')
        print('')
        time.sleep(1)
        print('Если вам помогли - введите слово "да".')
        print('')
        time.sleep(1)
        print('        Если не помогли - слово "нет".')
        print('')
        time.sleep(1)
        staff_assistance = (input('=> ')).lower()
        if staff_assistance == 'да':
            print('')
            time.sleep(1)
            print(f'Отлично! В этом отделе '
                  f'попытайтесь найти "{product_name}".')
        elif staff_assistance == 'нет':
            print('')
            time.sleep(1)
            print('Тогда, сначала как-то найдите нужный отдел, '
                  'а потом мы продолжим).')
            exit()
        else:
            print('')
            time.sleep(1)
            print('Слова "да" или "нет" записаны не правильно.')
            print('')
            time.sleep(1)
            print('Повторите пожалуйста ввод.')
            time.sleep(1)
            find_store_department(product_name)
    else:
        print('')
        print('Слова "да" или "нет" записаны не правильно.')
        print('')
        time.sleep(1)
        print('Повторите пожалуйста ввод.')
        time.sleep(1)
        find_store_department(product_name)


# Function for finding and buying sour cream.
def buy_sour_cream(need_fat_percentage, need_brand_name):
    need_brand_name = need_brand_name.capitalize()
    need_fat_percentage = (str(need_fat_percentage)).lower()
    time.sleep(1)
    print('')
    print(f'Вам нужен любой производитель, '
          f'кроме "{need_brand_name}" '
          f'только с {need_fat_percentage}% жирности.')
    print('')
    time.sleep(1)
    print('Если вы нашли то что нужно, введите имя производителя')
    brand_name = (input('=> ')).capitalize()
    print('')
    time.sleep(1)
    if brand_name == need_brand_name:
        print('Поищите что-то другое.')
        buy_sour_cream(need_fat_percentage, need_brand_name)
    else:
        time.sleep(1)
        print(f'Производитель "{brand_name}" вам подходит!')
        print('')
        time.sleep(1)
        print(f'Теперь введите величину процента жирности '
              f'написанного на банке "{brand_name}"')
        time.sleep(1)
        fat_percentage = str(input('=> ')).lower()
        print('')
        time.sleep(1)
        if fat_percentage == need_fat_percentage:
            print(f'Отлично! "{brand_name}" и '
                  f'жирность {fat_percentage}% - это то, что нужно!')
            time.sleep(1)
            print('')
            print('Если срок годности и цена вас устраивают,')
            time.sleep(1)
            print('')
            print('введите слово "да".')
            print('')
            time.sleep(1)
            print('Не устраивают - слово "нет".')
            final_confirmation = (input('=> ')).lower()
            if final_confirmation == 'да':
                print('')
                time.sleep(1)
                print('Задача была не из лёгких, но вы справились).')
                print('')
                time.sleep(1)
                print(f'Положите "{brand_name}" '
                      f'с {fat_percentage}% жирности')
                print('')
                time.sleep(1)
                print('себе в карзину и продолжайте шопинг.')
            elif final_confirmation == 'нет':
                print('')
                time.sleep(1)
                print('Тогда, придётся начать заново(')
                print('')
                time.sleep(1)
                buy_sour_cream(need_fat_percentage, need_brand_name)
            else:
                print('')
                time.sleep(1)
                print('Слова "да" или "нет" записаны не правильно.')
                print('')
                time.sleep(1)
                print('Повторите пожалуйста ввод.')
                time.sleep(1)
                buy_sour_cream(need_fat_percentage, need_brand_name)
        else:
            print(f'Жирность должна быть {need_fat_percentage}%, '
                  f'значит {fat_percentage}% - не подходит.')
            time.sleep(1)
            print('')
            print(f'Есть ли у производителя "{brand_name}" '
                  f'продукт с {need_fat_percentage}% жирности?')
            time.sleep(1)
            print('')
            print('Если есть - введите слово "да"')
            print('')
            time.sleep(1)
            print('Если нету - введите слово "нет".')
            fat_percentage_confirmation = (input('=> ')).lower()
            if fat_percentage_confirmation == 'да':
                print('')
                time.sleep(1)
                print('Отлично, вы нашли то что искали!')
                time.sleep(1)
                print('')
                print('Если срок годности и цена вас устраивают,')
                time.sleep(1)
                print('')
                print('введите слово "да"')
                print('')
                time.sleep(1)
                print('не устраивают - слово "нет".')
                final_confirmation = (input('=> ')).lower()
                if final_confirmation == 'да':
                    print('')
                    time.sleep(1)
                    print(f'Отлично! Положите "{brand_name}" '
                          f'с {need_fat_percentage}% жирности')
                    print('')
                    time.sleep(1)
                    print('себе в карзину и продолжайте шопинг '
                          'или идите к кассе.')
                    print('')
                    time.sleep(1)
                    print('Задача была не из лёгких, но вы справились).')
                elif final_confirmation == 'нет':
                    print('')
                    time.sleep(1)
                    print('Тогда, придётся начать заново(')
                    print('')
                    time.sleep(1)
                    buy_sour_cream(need_fat_percentage, need_brand_name)
                else:
                    print('')
                    time.sleep(1)
                    print('Слова "да" или "нет" записаны не правильно.')
                    print('')
                    time.sleep(1)
                    print('Повторите пожалуйста ввод.')
                    time.sleep(1)
                    buy_sour_cream(need_fat_percentage, need_brand_name)
            elif fat_percentage_confirmation == 'нет':
                print('')
                time.sleep(1)
                print('Тогда, к сожалению, придётся начать заново '
                      'и искать у других производителей')
                print('')
                time.sleep(1)
                buy_sour_cream(need_fat_percentage, need_brand_name)
            else:
                print('')
                time.sleep(1)
                print('Слова "да" или "нет" записаны не правильно.')
                print('')
                time.sleep(1)
                print('Повторите пожалуйста ввод.')
                time.sleep(1)
                buy_sour_cream(need_fat_percentage, need_brand_name)


# A function to find and buy something for tea.
def buy_something_for_tea():
    time.sleep(1)
    print('')
    print('Какой именно продукт вы выбрали?')
    time.sleep(1)
    print('')
    print('Введите пожалуйста название:')
    time.sleep(1)
    name_selected_product = (input('=> ')).capitalize()
    print('')
    time.sleep(1)
    print(f'"{name_selected_product}" - интересный выбор)')
    time.sleep(1)
    print('')
    print('Если срок годности и цена вас устраивают,')
    time.sleep(1)
    print('')
    print('введите слово "да"')
    print('')
    time.sleep(1)
    print('не устраивают - слово "нет".')
    final_confirmation = (input('=> ')).lower()
    if final_confirmation == 'да':
        print('')
        time.sleep(1)
        print(f'Отлично! Положите "{name_selected_product}"')
        print('')
        time.sleep(1)
        print('себе в карзину и идите к кассе.')
        print('')
        time.sleep(1)
        print('Вы проявили изобретательность! Поздравляю).')
    elif final_confirmation == 'нет':
        print('')
        time.sleep(1)
        print('Тогда, придётся начать заново(')
        print('')
        time.sleep(1)
        buy_something_for_tea()
    else:
        print('')
        time.sleep(1)
        print('Слова "да" или "нет" записаны не правильно.')
        print('')
        time.sleep(1)
        print('Повторите пожалуйста ввод.')
        time.sleep(1)
        buy_something_for_tea()
